/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 21
#define LARGE_STATE_COUNT 17
#define SYMBOL_COUNT 25
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_LPAREN = 1,
  anon_sym_RPAREN = 2,
  anon_sym_COLONaction = 3,
  sym_keyword = 4,
  sym_param = 5,
  aux_sym__float_token1 = 6,
  aux_sym__float_token2 = 7,
  aux_sym__float_token3 = 8,
  aux_sym__float_token4 = 9,
  aux_sym__integer_token1 = 10,
  aux_sym__integer_token2 = 11,
  sym_string = 12,
  sym_ident = 13,
  sym_comment = 14,
  sym_pddl = 15,
  sym_action = 16,
  sym_expression = 17,
  sym__atom = 18,
  sym_number = 19,
  sym__float = 20,
  sym__integer = 21,
  sym_list = 22,
  aux_sym_pddl_repeat1 = 23,
  aux_sym_action_repeat1 = 24,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COLONaction] = ":action",
  [sym_keyword] = "keyword",
  [sym_param] = "param",
  [aux_sym__float_token1] = "_float_token1",
  [aux_sym__float_token2] = "_float_token2",
  [aux_sym__float_token3] = "_float_token3",
  [aux_sym__float_token4] = "_float_token4",
  [aux_sym__integer_token1] = "_integer_token1",
  [aux_sym__integer_token2] = "_integer_token2",
  [sym_string] = "string",
  [sym_ident] = "ident",
  [sym_comment] = "comment",
  [sym_pddl] = "pddl",
  [sym_action] = "action",
  [sym_expression] = "expression",
  [sym__atom] = "_atom",
  [sym_number] = "number",
  [sym__float] = "_float",
  [sym__integer] = "_integer",
  [sym_list] = "list",
  [aux_sym_pddl_repeat1] = "pddl_repeat1",
  [aux_sym_action_repeat1] = "action_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COLONaction] = anon_sym_COLONaction,
  [sym_keyword] = sym_keyword,
  [sym_param] = sym_param,
  [aux_sym__float_token1] = aux_sym__float_token1,
  [aux_sym__float_token2] = aux_sym__float_token2,
  [aux_sym__float_token3] = aux_sym__float_token3,
  [aux_sym__float_token4] = aux_sym__float_token4,
  [aux_sym__integer_token1] = aux_sym__integer_token1,
  [aux_sym__integer_token2] = aux_sym__integer_token2,
  [sym_string] = sym_string,
  [sym_ident] = sym_ident,
  [sym_comment] = sym_comment,
  [sym_pddl] = sym_pddl,
  [sym_action] = sym_action,
  [sym_expression] = sym_expression,
  [sym__atom] = sym__atom,
  [sym_number] = sym_number,
  [sym__float] = sym__float,
  [sym__integer] = sym__integer,
  [sym_list] = sym_list,
  [aux_sym_pddl_repeat1] = aux_sym_pddl_repeat1,
  [aux_sym_action_repeat1] = aux_sym_action_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLONaction] = {
    .visible = true,
    .named = false,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_param] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__float_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__float_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__float_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__float_token4] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__integer_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__integer_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_pddl] = {
    .visible = true,
    .named = true,
  },
  [sym_action] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym__atom] = {
    .visible = false,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym__float] = {
    .visible = false,
    .named = true,
  },
  [sym__integer] = {
    .visible = false,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_pddl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_action_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
};

static const TSSymbol ts_supertype_symbols[SUPERTYPE_COUNT] = {
  sym_expression,
};

static const TSMapSlice ts_supertype_map_slices[] = {
  [sym_expression] = {.index = 0, .length = 6},
};

static const TSSymbol ts_supertype_map_entries[] = {
  [0] =
    sym_ident,
    sym_keyword,
    sym_list,
    sym_number,
    sym_param,
    sym_string,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(14);
      ADVANCE_MAP(
        '"', 41,
        '#', 55,
        '(', 15,
        ')', 16,
        '+', 46,
        '-', 45,
        '.', 57,
        '1', 32,
        ':', 9,
        ';', 62,
        '?', 12,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (lookahead != 0) ADVANCE(61);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 41,
        '#', 55,
        '(', 15,
        ')', 16,
        '+', 46,
        '-', 45,
        '.', 57,
        '1', 32,
        ':', 11,
        ';', 62,
        '?', 12,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (lookahead != 0) ADVANCE(61);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(39);
      if (lookahead == '\\') ADVANCE(13);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '+') ADVANCE(7);
      END_STATE();
    case 4:
      if (lookahead == '0') ADVANCE(10);
      END_STATE();
    case 5:
      if (lookahead == ';') ADVANCE(62);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ':' &&
          lookahead != ';' &&
          lookahead != '?') ADVANCE(61);
      END_STATE();
    case 6:
      if (lookahead == 'F') ADVANCE(30);
      END_STATE();
    case 7:
      if (lookahead == 'I') ADVANCE(8);
      END_STATE();
    case 8:
      if (lookahead == 'N') ADVANCE(6);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(18);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(23);
      END_STATE();
    case 10:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(3);
      END_STATE();
    case 11:
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(23);
      END_STATE();
    case 12:
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(24);
      END_STATE();
    case 13:
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_COLONaction);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(23);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_keyword);
      if (lookahead == 'c') ADVANCE(22);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(23);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_keyword);
      if (lookahead == 'i') ADVANCE(21);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(23);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_keyword);
      if (lookahead == 'n') ADVANCE(17);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(23);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_keyword);
      if (lookahead == 'o') ADVANCE(20);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(23);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_keyword);
      if (lookahead == 't') ADVANCE(19);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(23);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_keyword);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_param);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym__float_token1);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(61);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym__float_token1);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(61);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym__float_token2);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(61);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym__float_token2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(61);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym__float_token3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(61);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym__float_token4);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym__float_token4);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(61);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym__integer_token1);
      if (lookahead == '.') ADVANCE(36);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(47);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '(' ||
          lookahead == ')' ||
          lookahead == ';') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(48);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym__integer_token1);
      if (lookahead == '.') ADVANCE(37);
      if (lookahead == '0') ADVANCE(35);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(58);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(61);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym__integer_token1);
      if (lookahead == '.') ADVANCE(37);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(61);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym__integer_token1);
      if (lookahead == '.') ADVANCE(37);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(61);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym__integer_token1);
      if (lookahead == '0') ADVANCE(25);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(61);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym__integer_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(61);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym__integer_token2);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(61);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_string);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(61);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '"') ADVANCE(40);
      if (lookahead == '\\') ADVANCE(56);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '(' ||
          lookahead == ')' ||
          lookahead == ';') ADVANCE(2);
      if (lookahead != 0) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '+') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(61);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '+') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(61);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '+') ADVANCE(50);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(61);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '.') ADVANCE(57);
      if (lookahead == '1') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(61);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '.') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(61);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '0') ADVANCE(27);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(61);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '0') ADVANCE(54);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(61);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'F') ADVANCE(31);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(61);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'I') ADVANCE(51);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(61);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'N') ADVANCE(49);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(61);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'r') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(53);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(61);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'r') ADVANCE(60);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(61);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(44);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(61);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'b' ||
          lookahead == 'o' ||
          lookahead == 'x') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(61);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_ident);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '(' ||
          lookahead == ')' ||
          lookahead == ';') ADVANCE(2);
      if (lookahead != 0) ADVANCE(41);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_ident);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(61);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_ident);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(61);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_ident);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(61);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_ident);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(61);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';') ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(62);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 5},
  [20] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COLONaction] = ACTIONS(1),
    [sym_keyword] = ACTIONS(1),
    [sym_param] = ACTIONS(1),
    [aux_sym__float_token1] = ACTIONS(1),
    [aux_sym__float_token2] = ACTIONS(1),
    [aux_sym__float_token3] = ACTIONS(1),
    [aux_sym__float_token4] = ACTIONS(1),
    [aux_sym__integer_token1] = ACTIONS(1),
    [aux_sym__integer_token2] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_ident] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_pddl] = STATE(18),
    [anon_sym_LPAREN] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym_action] = STATE(3),
    [sym_expression] = STATE(3),
    [sym__atom] = STATE(11),
    [sym_number] = STATE(11),
    [sym__float] = STATE(12),
    [sym__integer] = STATE(12),
    [sym_list] = STATE(11),
    [aux_sym_pddl_repeat1] = STATE(3),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(9),
    [sym_keyword] = ACTIONS(11),
    [sym_param] = ACTIONS(11),
    [aux_sym__float_token1] = ACTIONS(13),
    [aux_sym__float_token2] = ACTIONS(13),
    [aux_sym__float_token3] = ACTIONS(13),
    [aux_sym__float_token4] = ACTIONS(13),
    [aux_sym__integer_token1] = ACTIONS(13),
    [aux_sym__integer_token2] = ACTIONS(13),
    [sym_string] = ACTIONS(15),
    [sym_ident] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym_action] = STATE(5),
    [sym_expression] = STATE(5),
    [sym__atom] = STATE(11),
    [sym_number] = STATE(11),
    [sym__float] = STATE(12),
    [sym__integer] = STATE(12),
    [sym_list] = STATE(11),
    [aux_sym_pddl_repeat1] = STATE(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(17),
    [sym_keyword] = ACTIONS(11),
    [sym_param] = ACTIONS(11),
    [aux_sym__float_token1] = ACTIONS(13),
    [aux_sym__float_token2] = ACTIONS(13),
    [aux_sym__float_token3] = ACTIONS(13),
    [aux_sym__float_token4] = ACTIONS(13),
    [aux_sym__integer_token1] = ACTIONS(13),
    [aux_sym__integer_token2] = ACTIONS(13),
    [sym_string] = ACTIONS(15),
    [sym_ident] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(4)] = {
    [sym_expression] = STATE(8),
    [sym__atom] = STATE(11),
    [sym_number] = STATE(11),
    [sym__float] = STATE(12),
    [sym__integer] = STATE(12),
    [sym_list] = STATE(11),
    [aux_sym_action_repeat1] = STATE(8),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_RPAREN] = ACTIONS(21),
    [anon_sym_COLONaction] = ACTIONS(23),
    [sym_keyword] = ACTIONS(15),
    [sym_param] = ACTIONS(11),
    [aux_sym__float_token1] = ACTIONS(13),
    [aux_sym__float_token2] = ACTIONS(13),
    [aux_sym__float_token3] = ACTIONS(13),
    [aux_sym__float_token4] = ACTIONS(13),
    [aux_sym__integer_token1] = ACTIONS(13),
    [aux_sym__integer_token2] = ACTIONS(13),
    [sym_string] = ACTIONS(15),
    [sym_ident] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(5)] = {
    [sym_action] = STATE(5),
    [sym_expression] = STATE(5),
    [sym__atom] = STATE(11),
    [sym_number] = STATE(11),
    [sym__float] = STATE(12),
    [sym__integer] = STATE(12),
    [sym_list] = STATE(11),
    [aux_sym_pddl_repeat1] = STATE(5),
    [anon_sym_LPAREN] = ACTIONS(25),
    [anon_sym_RPAREN] = ACTIONS(28),
    [sym_keyword] = ACTIONS(30),
    [sym_param] = ACTIONS(30),
    [aux_sym__float_token1] = ACTIONS(33),
    [aux_sym__float_token2] = ACTIONS(33),
    [aux_sym__float_token3] = ACTIONS(33),
    [aux_sym__float_token4] = ACTIONS(33),
    [aux_sym__integer_token1] = ACTIONS(33),
    [aux_sym__integer_token2] = ACTIONS(33),
    [sym_string] = ACTIONS(36),
    [sym_ident] = ACTIONS(36),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(6)] = {
    [sym_expression] = STATE(8),
    [sym__atom] = STATE(11),
    [sym_number] = STATE(11),
    [sym__float] = STATE(12),
    [sym__integer] = STATE(12),
    [sym_list] = STATE(11),
    [aux_sym_action_repeat1] = STATE(8),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_RPAREN] = ACTIONS(21),
    [sym_keyword] = ACTIONS(11),
    [sym_param] = ACTIONS(11),
    [aux_sym__float_token1] = ACTIONS(13),
    [aux_sym__float_token2] = ACTIONS(13),
    [aux_sym__float_token3] = ACTIONS(13),
    [aux_sym__float_token4] = ACTIONS(13),
    [aux_sym__integer_token1] = ACTIONS(13),
    [aux_sym__integer_token2] = ACTIONS(13),
    [sym_string] = ACTIONS(15),
    [sym_ident] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(7)] = {
    [sym_expression] = STATE(7),
    [sym__atom] = STATE(11),
    [sym_number] = STATE(11),
    [sym__float] = STATE(12),
    [sym__integer] = STATE(12),
    [sym_list] = STATE(11),
    [aux_sym_action_repeat1] = STATE(7),
    [anon_sym_LPAREN] = ACTIONS(39),
    [anon_sym_RPAREN] = ACTIONS(42),
    [sym_keyword] = ACTIONS(44),
    [sym_param] = ACTIONS(44),
    [aux_sym__float_token1] = ACTIONS(47),
    [aux_sym__float_token2] = ACTIONS(47),
    [aux_sym__float_token3] = ACTIONS(47),
    [aux_sym__float_token4] = ACTIONS(47),
    [aux_sym__integer_token1] = ACTIONS(47),
    [aux_sym__integer_token2] = ACTIONS(47),
    [sym_string] = ACTIONS(50),
    [sym_ident] = ACTIONS(50),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(8)] = {
    [sym_expression] = STATE(7),
    [sym__atom] = STATE(11),
    [sym_number] = STATE(11),
    [sym__float] = STATE(12),
    [sym__integer] = STATE(12),
    [sym_list] = STATE(11),
    [aux_sym_action_repeat1] = STATE(7),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_RPAREN] = ACTIONS(53),
    [sym_keyword] = ACTIONS(11),
    [sym_param] = ACTIONS(11),
    [aux_sym__float_token1] = ACTIONS(13),
    [aux_sym__float_token2] = ACTIONS(13),
    [aux_sym__float_token3] = ACTIONS(13),
    [aux_sym__float_token4] = ACTIONS(13),
    [aux_sym__integer_token1] = ACTIONS(13),
    [aux_sym__integer_token2] = ACTIONS(13),
    [sym_string] = ACTIONS(15),
    [sym_ident] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(9)] = {
    [sym_expression] = STATE(10),
    [sym__atom] = STATE(11),
    [sym_number] = STATE(11),
    [sym__float] = STATE(12),
    [sym__integer] = STATE(12),
    [sym_list] = STATE(11),
    [aux_sym_action_repeat1] = STATE(10),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_RPAREN] = ACTIONS(55),
    [sym_keyword] = ACTIONS(11),
    [sym_param] = ACTIONS(11),
    [aux_sym__float_token1] = ACTIONS(13),
    [aux_sym__float_token2] = ACTIONS(13),
    [aux_sym__float_token3] = ACTIONS(13),
    [aux_sym__float_token4] = ACTIONS(13),
    [aux_sym__integer_token1] = ACTIONS(13),
    [aux_sym__integer_token2] = ACTIONS(13),
    [sym_string] = ACTIONS(15),
    [sym_ident] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(10)] = {
    [sym_expression] = STATE(7),
    [sym__atom] = STATE(11),
    [sym_number] = STATE(11),
    [sym__float] = STATE(12),
    [sym__integer] = STATE(12),
    [sym_list] = STATE(11),
    [aux_sym_action_repeat1] = STATE(7),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_RPAREN] = ACTIONS(57),
    [sym_keyword] = ACTIONS(11),
    [sym_param] = ACTIONS(11),
    [aux_sym__float_token1] = ACTIONS(13),
    [aux_sym__float_token2] = ACTIONS(13),
    [aux_sym__float_token3] = ACTIONS(13),
    [aux_sym__float_token4] = ACTIONS(13),
    [aux_sym__integer_token1] = ACTIONS(13),
    [aux_sym__integer_token2] = ACTIONS(13),
    [sym_string] = ACTIONS(15),
    [sym_ident] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(11)] = {
    [anon_sym_LPAREN] = ACTIONS(59),
    [anon_sym_RPAREN] = ACTIONS(59),
    [sym_keyword] = ACTIONS(59),
    [sym_param] = ACTIONS(59),
    [aux_sym__float_token1] = ACTIONS(61),
    [aux_sym__float_token2] = ACTIONS(61),
    [aux_sym__float_token3] = ACTIONS(61),
    [aux_sym__float_token4] = ACTIONS(61),
    [aux_sym__integer_token1] = ACTIONS(61),
    [aux_sym__integer_token2] = ACTIONS(61),
    [sym_string] = ACTIONS(61),
    [sym_ident] = ACTIONS(61),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(12)] = {
    [anon_sym_LPAREN] = ACTIONS(63),
    [anon_sym_RPAREN] = ACTIONS(63),
    [sym_keyword] = ACTIONS(63),
    [sym_param] = ACTIONS(63),
    [aux_sym__float_token1] = ACTIONS(65),
    [aux_sym__float_token2] = ACTIONS(65),
    [aux_sym__float_token3] = ACTIONS(65),
    [aux_sym__float_token4] = ACTIONS(65),
    [aux_sym__integer_token1] = ACTIONS(65),
    [aux_sym__integer_token2] = ACTIONS(65),
    [sym_string] = ACTIONS(65),
    [sym_ident] = ACTIONS(65),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(13)] = {
    [anon_sym_LPAREN] = ACTIONS(67),
    [anon_sym_RPAREN] = ACTIONS(67),
    [sym_keyword] = ACTIONS(67),
    [sym_param] = ACTIONS(67),
    [aux_sym__float_token1] = ACTIONS(69),
    [aux_sym__float_token2] = ACTIONS(69),
    [aux_sym__float_token3] = ACTIONS(69),
    [aux_sym__float_token4] = ACTIONS(69),
    [aux_sym__integer_token1] = ACTIONS(69),
    [aux_sym__integer_token2] = ACTIONS(69),
    [sym_string] = ACTIONS(69),
    [sym_ident] = ACTIONS(69),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(14)] = {
    [anon_sym_LPAREN] = ACTIONS(71),
    [anon_sym_RPAREN] = ACTIONS(71),
    [sym_keyword] = ACTIONS(71),
    [sym_param] = ACTIONS(71),
    [aux_sym__float_token1] = ACTIONS(73),
    [aux_sym__float_token2] = ACTIONS(73),
    [aux_sym__float_token3] = ACTIONS(73),
    [aux_sym__float_token4] = ACTIONS(73),
    [aux_sym__integer_token1] = ACTIONS(73),
    [aux_sym__integer_token2] = ACTIONS(73),
    [sym_string] = ACTIONS(73),
    [sym_ident] = ACTIONS(73),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(15)] = {
    [anon_sym_LPAREN] = ACTIONS(75),
    [anon_sym_RPAREN] = ACTIONS(75),
    [sym_keyword] = ACTIONS(75),
    [sym_param] = ACTIONS(75),
    [aux_sym__float_token1] = ACTIONS(77),
    [aux_sym__float_token2] = ACTIONS(77),
    [aux_sym__float_token3] = ACTIONS(77),
    [aux_sym__float_token4] = ACTIONS(77),
    [aux_sym__integer_token1] = ACTIONS(77),
    [aux_sym__integer_token2] = ACTIONS(77),
    [sym_string] = ACTIONS(77),
    [sym_ident] = ACTIONS(77),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(16)] = {
    [anon_sym_LPAREN] = ACTIONS(79),
    [anon_sym_RPAREN] = ACTIONS(79),
    [sym_keyword] = ACTIONS(79),
    [sym_param] = ACTIONS(79),
    [aux_sym__float_token1] = ACTIONS(81),
    [aux_sym__float_token2] = ACTIONS(81),
    [aux_sym__float_token3] = ACTIONS(81),
    [aux_sym__float_token4] = ACTIONS(81),
    [aux_sym__integer_token1] = ACTIONS(81),
    [aux_sym__integer_token2] = ACTIONS(81),
    [sym_string] = ACTIONS(81),
    [sym_ident] = ACTIONS(81),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      ts_builtin_sym_end,
  [7] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      ts_builtin_sym_end,
  [14] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      sym_ident,
  [21] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(17)] = 0,
  [SMALL_STATE(18)] = 7,
  [SMALL_STATE(19)] = 14,
  [SMALL_STATE(20)] = 21,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pddl_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pddl_repeat1, 2, 0, 0),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pddl_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pddl_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pddl_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_action_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_action_repeat1, 2, 0, 0),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_action_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_action_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_action_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_action, 4, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_action, 4, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_action, 5, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_action, 5, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pddl, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pddl, 3, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_pddl(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .supertype_map_slices = ts_supertype_map_slices,
    .supertype_map_entries = ts_supertype_map_entries,
    .supertype_symbols = ts_supertype_symbols,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "pddl",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
